# Generated by Django 6.0.6 on 2026-06-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='vehicle',
        ),
    ]
